version: "3.9"
services:

  postgres:
    image: docker.io/library/postgres:18-alpine@sha256:77f585114c32fbca283dc835b0596f4e52b51b4c6662d7810b2f4084f60a1873
    network_mode: host
    # ports:
    #   - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD: password

  minio:
    image: quay.io/minio/minio:latest@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e
    command: [ "server", "/data", "--console-address", ":9001" ]
    network_mode: host
    # ports:
    #   - "9001:9001"
    #   - "9000:9000"
    deploy:
      restart_policy:
        condition: on-failure

  aws-cli:
    depends_on:
      - minio
    image: docker.io/amazon/aws-cli@sha256:ce44b800602264c12298bbf3399055a4cefdb9ed4a098abe564afe26e7071bce
    entrypoint: aws
    network_mode: host
    command:
      [
        "--endpoint-url",
        "http://localhost:9000",
        "s3api",
        "create-bucket",
        "--bucket",
        "terrashine"
      ]
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: us-east-1

  generate-certificates:
    image: docker.io/alpine/openssl@sha256:615bd9e1af5c7683d785c139edf6a05adc9e45747267fb58223001f327da6861
    entrypoint: /mnt/scripts/generate-test-certificate
    working_dir: /mnt/
    volumes:
      - source: ./resources/
        target: /mnt/resources/
        type: bind
      - source: ./scripts/
        target: /mnt/scripts/
        type: bind

  nginx:
    image: docker.io/library/nginx@sha256:f9ea18bfa4fad859e1ed38259d711da7ccad2c3516e875cec3351a57c859f571
    network_mode: host
    volumes:
      - ./resources/test/nginx:/etc/nginx:ro
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - generate-certificates
  #terrashine:
  #  image: docker.io/library/rust
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
