name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - name: Ensure musl installed
        run: sudo apt-get install -y musl-dev musl-tools musl && rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-musl && cargo install cross

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Build final release binary
        run: ./scripts/release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: Test-release
          files: |
            terrashine-x86_64-unknown-linux-musl.tar.gz
            terrashine-aarch64-unknown-linux-musl.tar.gz
            LICENSE