name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    steps:

      - name: Ensure musl installed
        run: sudo apt-get install -y musl-dev musl-tools musl && rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-musl && cargo install cross

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6


      # Add Docker login step
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build final release binary
        run: ./scripts/release ${{ github.ref_name }}

      - name: Release files
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2
        with:
          draft: true
          files: |
            terrashine-x86_64-unknown-linux-musl.tar.gz
            terrashine-aarch64-unknown-linux-musl.tar.gz
            LICENSE
