name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    steps:

      - name: Ensure musl installed
        run: sudo apt-get install -y musl-dev musl-tools musl && rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-musl && cargo install cross

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7


      # Add Docker login step
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build final release binary
        run: ./scripts/release ${{ github.ref_name }}

      - name: Release files
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        with:
          draft: true
          files: |
            terrashine-x86_64-unknown-linux-musl.tar.gz
            terrashine-aarch64-unknown-linux-musl.tar.gz
            LICENSE
