name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    steps:

      - name: Ensure musl installed
        run: sudo apt-get install -y musl-dev musl-tools musl && rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-musl && cargo install cross

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5


      # Add Docker login step
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build final release binary
        run: ./scripts/release ${{ github.ref_name }}

      - name: Release files
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            terrashine-x86_64-unknown-linux-musl.tar.gz
            terrashine-aarch64-unknown-linux-musl.tar.gz
            LICENSE
